from collections import OrderedDict


SETUP_WRITES = [
    {"addr": 0x38FA4, "start_bit": 25, "size": 1, "value": 1},
    {"addr": 0x38FB4, "start_bit": 25, "size": 1, "value": 1},
]


UNITS = OrderedDict([
    ("TPT", {
        "en_addr": 0x0A6120,
        "enable_bit": 30,
        "start_addr": 0x0A6124,
        "selector_addr": 0x0A6100,
        "value_addr": 0x0A6140,
        "size": 16,
    }),
    ("PXDP", {
        "en_addr": 0x144020,
        "enable_bit": 30,
        "start_addr": 0x144024,
        "selector_addr": 0x144000,
        "value_addr": 0x144040,
        "size": 16,
    }),
    ("PXTL", {
        "en_addr": 0x10E420,
        "enable_bit": 30,
        "start_addr": 0x10E424,
        "selector_addr": 0x10E400,
        "value_addr": 0x10E440,
        "size": 16,
    }),
    ("PXTH", {
        "en_addr": 0x20F020,
        "enable_bit": 30,
        "start_addr": 0x20F024,
        "selector_addr": 0x20F000,
        "value_addr": 0x20F040,
        "size": 16,
    }),
    ("RXB", {
        "en_addr": 0x268720,
        "enable_bit": 30,
        "start_addr": 0x268724,
        "selector_addr": 0x268700,
        "value_addr": 0x268740,
        "size": 16,
    }),
    ("RXT", {
        "en_addr": 0x05A220,
        "enable_bit": 30,
        "start_addr": 0x05A224,
        "selector_addr": 0x05A200,
        "value_addr": 0x05A240,
        "size": 16,
    }),
    ("RXW", {
        "en_addr": 0x065420,
        "enable_bit": 30,
        "start_addr": 0x065424,
        "selector_addr": 0x065400,
        "value_addr": 0x065440,
        "size": 16,
    }),
    ("RXS", {
        "en_addr": 0x074920,
        "enable_bit": 30,
        "start_addr": 0x074924,
        "selector_addr": 0x074900,
        "value_addr": 0x074940,
        "size": 16,
    }),
    ("RXC", {
        "en_addr": 0x086E20,
        "enable_bit": 30,
        "start_addr": 0x086E24,
        "selector_addr": 0x086E00,
        "value_addr": 0x086E40,
        "size": 16,
    }),
    ("SXP", {
        "en_addr": 0x038920,
        "enable_bit": 30,
        "start_addr": 0x038924,
        "selector_addr": 0x038900,
        "value_addr": 0x038940,
        "size": 16,
    }),
    ("SXS_E2E_CACHE", {
        "en_addr": 0x044720,
        "enable_bit": 30,
        "start_addr": 0x044724,
        "selector_addr": 0x044700,
        "value_addr": 0x044740,
        "size": 16,
    }),
    ("SXW", {
        "en_addr": 0x02CD20,
        "enable_bit": 30,
        "start_addr": 0x02CD24,
        "selector_addr": 0x02CD00,
        "value_addr": 0x02CD40,
        "size": 16,
    }),
    ("SXD", {
        "en_addr": 0x01D620,
        "enable_bit": 30,
        "start_addr": 0x01D624,
        "selector_addr": 0x01D600,
        "value_addr": 0x01D640,
        "size": 16,
    }),
    ("SXS", {
        "en_addr": 0x046420,
        "enable_bit": 30,
        "start_addr": 0x046424,
        "selector_addr": 0x046400,
        "value_addr": 0x046440,
        "size": 16,
    }),
    ("RXPS", {
        "en_addr": 0x043220,
        "enable_bit": 30,
        "start_addr": 0x043224,
        "selector_addr": 0x043200,
        "value_addr": 0x043240,
        "size": 16,
    }),
    ("RXPS_E2E_CACHE", {
        "en_addr": 0x040120,
        "enable_bit": 30,
        "start_addr": 0x040124,
        "selector_addr": 0x040100,
        "value_addr": 0x040140,
        "size": 16,
    }),
])


COUNTERS = [
    ("TPT", 77, "mlx5_tpt_l0_mtt_hit", "Level 0 MTT cache hits", "events"),
    ("TPT", 76, "mlx5_tpt_l0_mtt_miss", "Level 0 MTT cache misses", "events"),
    ("TPT", 82, "mlx5_tpt_l1_mtt_hit", "Level 1 MTT cache hits", "events"),
    ("TPT", 81, "mlx5_tpt_l1_mtt_miss", "Level 1 MTT cache misses", "events"),
    ("TPT", 55, "mlx5_tpt_l0_mpt_hit", "Level 0 MPT cache hits", "events"),
    ("TPT", 54, "mlx5_tpt_l0_mpt_miss", "Level 0 MPT cache misses", "events"),
    ("TPT", 60, "mlx5_tpt_l1_mpt_hit", "Level 1 MPT cache hits", "events"),
    ("TPT", 59, "mlx5_tpt_l1_mpt_miss", "Level 1 MPT cache misses", "events"),
    ("TPT", 71, "mlx5_tpt_indirect_mem_key", "Indirect memory key accesses", "events"),

    ("PXTH", 0, "mlx5_pxt_icm_cache_miss", "ICM cache misses (reads from host memory)", "events"),

    ("PXTL", 270, "mlx5_pxt_pcie_internal_bp", "PCIe internal back pressure cycles", "cycles"),
    ("PXTL", 246, "mlx5_pxt_outbound_stalled_reads", "Outbound stalled read cycles", "cycles"),
    ("PXTL", 254, "mlx5_pxt_outbound_stalled_writes", "Outbound stalled write cycles", "cycles"),
    ("PXTL", 446, "mlx5_pxt_read_stuck_no_engines", "PCIe read stalled no read engines", "cycles"),
    ("PXTL", 438, "mlx5_pxt_read_stuck_byte_limit", "PCIe read stalled byte limit", "cycles"),
    ("PXTL", 406, "mlx5_pxt_read_stuck_ordering", "PCIe read stalled ordering rules", "cycles"),

    ("RXB", 57, "mlx5_rxb_bw_64b_1", "RX packet buffer 64B units port 1", "events"),
    ("RXB", 56, "mlx5_rxb_packets_1", "RX packet buffer packets port 1", "events"),
    ("RXB", 55, "mlx5_rxb_bw_64b_0", "RX packet buffer 64B units port 0", "events"),
    ("RXB", 13, "mlx5_rxb_packets_0", "RX packet buffer packets port 0", "events"),
    ("RXB", 15, "mlx5_rxb_rxs_no_credits", "Back pressure from scatter to RX buffer", "cycles"),
    ("RXB", 19, "mlx5_rxb_rxt_no_credits", "Back pressure from RX translation to RX buffer", "cycles"),
    ("RXB", 50, "mlx5_rxb_port0_buffer_full", "RX packet buffer full cycles on port 0", "cycles"),
    ("RXB", 52, "mlx5_rxb_port1_buffer_full", "RX packet buffer full cycles on port 1", "cycles"),

    ("RXPS", 0, "mlx5_device_clocks_wraparound", "Chip device clock wraparound counter", "events"),
    ("RXPS", 0, "mlx5_device_clocks", "Chip frequency device clocks", "events"),
    ("RXPS", 72, "mlx5_rxps_steering0_work_rate", "RX post-steering pipe 0 events", "events"),
    ("RXPS", 53, "mlx5_rxps_steering1_work_rate", "RX post-steering pipe 1 events", "events"),
    ("RXPS", 69, "mlx5_rxps_steering0_cache_hit", "RX post-steering cache hit pipe 0", "events"),
    ("RXPS", 68, "mlx5_rxps_steering0_cache_miss", "RX post-steering cache miss pipe 0", "events"),
    ("RXPS", 50, "mlx5_rxps_steering1_cache_hit", "RX post-steering cache hit pipe 1", "events"),
    ("RXPS", 49, "mlx5_rxps_steering1_cache_miss", "RX post-steering cache miss pipe 1", "events"),
    ("RXPS", 67, "mlx5_rxps_steering0_cache_total", "RX post-steering cache accesses pipe 0", "events"),
    ("RXPS", 48, "mlx5_rxps_steering1_cache_total", "RX post-steering cache accesses pipe 1", "events"),

    ("RXPS_E2E_CACHE", 15, "mlx5_rxps_e2e_cache_total", "RX steering learning cache lookups", "events"),
    ("RXPS_E2E_CACHE", 24, "mlx5_rxps_e2e_cache_hit", "RX steering learning cache hits", "events"),
    ("RXPS_E2E_CACHE", 33, "mlx5_rxps_e2e_cache_miss", "RX steering learning cache misses", "events"),
    ("RXPS_E2E_CACHE", 42, "mlx5_rxps_e2e_cache_learn", "RX steering learning cache learned rules", "events"),

    ("RXW", 98, "mlx5_rxw_tpt_bp", "Back pressure from MMU to RX descriptor handling", "cycles"),
    ("RXW", 102, "mlx5_rxw_wqe_cache_hit", "Receive WQE cache hits", "events"),
    ("RXW", 103, "mlx5_rxw_wqe_cache_miss", "Receive WQE cache misses", "events"),

    ("RXS", 37, "mlx5_rxs_no_pxt_credits", "Back pressure from PCIe to packet scatter", "cycles"),

    ("RXT", 21, "mlx5_rxt_slice_load_slow", "RX packets that went through steering", "events"),
    ("RXT", 20, "mlx5_rxt_slice_load_fast", "RX packets that went through fast-path steering", "events"),

    ("PXDP", 50, "mlx5_pxdp_rx_128b_total", "PCIe RX 128B total units", "events"),
    ("PXDP", 49, "mlx5_pxdp_rx_128b_data", "PCIe RX 128B data units", "events"),
    ("PXDP", 136, "mlx5_pxdp_tx_128b_data", "PCIe TX 128B data units", "events"),

    ("RXC", 104, "mlx5_rxc_eq_all_busy", "EQ all state machines busy cycles", "cycles"),
    ("RXC", 180, "mlx5_rxc_cq_all_busy", "CQ all state machines busy cycles", "cycles"),
    ("RXC", 43, "mlx5_rxc_msix_all_busy", "MSI-X all state machines busy cycles", "cycles"),
    ("RXC", 99, "mlx5_rxc_cqe_compressed", "Compressed CQEs", "events"),
    ("RXC", 109, "mlx5_rxc_zip_close_eqe", "CQE zip sessions closed due to EQE", "events"),
    ("RXC", 113, "mlx5_rxc_zip_close_timeout", "CQE zip sessions closed due to timeout", "events"),
    ("RXC", 119, "mlx5_rxc_zip_close_mismatch", "CQE zip sessions closed due to mismatch", "events"),
    ("RXC", 120, "mlx5_rxc_zip_close_px_idle", "CQE zip sessions closed due to PCIe idle", "events"),
    ("RXC", 121, "mlx5_rxc_zip_close_s2cqe", "CQE zip sessions closed due to scatter-to-CQE", "events"),
    ("RXC", 100, "mlx5_rxc_zip_writing_8cqes", "CQE zip strides with 8 CQEs", "events"),
    ("RXC", 122, "mlx5_rxc_zip_close_lro", "CQE zip sessions closed due to LRO", "events"),

    ("SXW", 279, "mlx5_sxw_done_limited", "TX descriptor stopped limited state", "events"),
    ("SXW", 284, "mlx5_sxw_done_vl_limited", "TX descriptor stopped VL back pressure", "events"),
    ("SXW", 283, "mlx5_sxw_done_desched", "TX descriptor stopped de-schedule", "events"),
    ("SXW", 280, "mlx5_sxw_done_work_done", "TX descriptor stopped work done", "events"),
    ("SXW", 278, "mlx5_sxw_done_e2e_credits", "TX descriptor stopped E2E credits", "events"),
    ("SXW", 31, "mlx5_sxw_tx_packets", "TX packets", "events"),

    ("SXP", 47, "mlx5_sxp_line_port0", "Lines transmitted on port 0", "events"),
    ("SXP", 46, "mlx5_sxp_line_port1", "Lines transmitted on port 1", "events"),
    ("SXP", 45, "mlx5_sxp_line_loopback", "Loopback lines transmitted", "events"),
    ("SXP", 23, "mlx5_sxp_bw_64b_0", "TX bandwidth counter 64B units port 0", "events"),
    ("SXP", 24, "mlx5_sxp_packets_0", "TX packet counter port 0", "events"),

    ("SXS", 24, "mlx5_sxp_steering0_work_rate", "TX steering pipe 0 events", "events"),
    ("SXS", 26, "mlx5_sxp_steering1_work_rate", "TX steering pipe 1 events", "events"),
    ("SXS", 40, "mlx5_sxp_steering0_hit", "TX steering hits on pipe 0", "events"),
    ("SXS", 38, "mlx5_sxp_steering0_miss", "TX steering misses on pipe 0", "events"),
    ("SXS", 41, "mlx5_sxp_steering1_hit", "TX steering hits on pipe 1", "events"),
    ("SXS", 39, "mlx5_sxp_steering1_miss", "TX steering misses on pipe 1", "events"),
    ("SXS", 30, "mlx5_sxp_steering0_cache_hit", "TX steering rule-cache hits on pipe 0", "events"),
    ("SXS", 35, "mlx5_sxp_steering1_cache_hit", "TX steering rule-cache hits on pipe 1", "events"),
    ("SXS", 29, "mlx5_sxp_steering0_cache_miss", "TX steering rule-cache misses on pipe 0", "events"),
    ("SXS", 34, "mlx5_sxp_steering1_cache_miss", "TX steering rule-cache misses on pipe 1", "events"),
    ("SXS", 28, "mlx5_sxp_steering0_cache_total", "TX steering rule-cache accesses on pipe 0", "events"),
    ("SXS", 33, "mlx5_sxp_steering1_cache_total", "TX steering rule-cache accesses on pipe 1", "events"),

    ("SXS_E2E_CACHE", 15, "mlx5_sxp_e2e_cache_total", "TX steering learning cache lookups", "events"),
    ("SXS_E2E_CACHE", 24, "mlx5_sxp_e2e_cache_hit", "TX steering learning cache hits", "events"),
    ("SXS_E2E_CACHE", 33, "mlx5_sxp_e2e_cache_miss", "TX steering learning cache misses", "events"),
    ("SXS_E2E_CACHE", 42, "mlx5_sxp_e2e_cache_learn", "TX steering learning cache learned rules", "events"),
]
